const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let state=null, selected=new Set(), busy=false, lastMessageCount=0, lastQuestSig='', lastFarmSig='', lastNavSig='', spotLevelInitialized=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lines=id=>$(id).value.split('\n').map(x=>x.trim()).filter(Boolean);
function toast(text,error=false){const el=$('#toast');el.textContent=text;el.className=error?'show error':'show';setTimeout(()=>el.className='',2600)}
async function post(path,data){const r=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});const out=await r.json();if(!r.ok)throw Error(out.error||r.statusText);toast(out.task?`Task set: ${out.task}`:'Command accepted');return out}
function bar(label,value,max,cls=''){const pct=Math.max(0,Math.min(100,(+value||0)/Math.max(1,+max||1)*100));return `<div class="vital"><b>${label}</b><div class="bar ${cls}"><i style="width:${pct}%"></i></div><span>${value||0} / ${max||0}</span></div>`}
function renderHeader(){const on=state.phase==='playing';$('#connection-dot').classList.toggle('on',on);$('#connection').textContent=state.phase;$('#character').textContent=state.character||'No character';$('#location').textContent=state.map.path||'Waiting for map'}
function xpNumber(value){return Math.max(0,+value||0).toLocaleString()}
function renderStats(){const s=state.stats,lp=state.level_progress||{};$("#level").textContent=s.level??"—";$("#level").title=lp.next_experience==null?`${xpNumber(lp.experience)} XP · maximum tracked level`:`${xpNumber(lp.experience)} / ${xpNumber(lp.next_experience)} XP · ${xpNumber(lp.remaining_experience)} remaining · ${lp.progress_percent??0}%`;$("#vitals").innerHTML=bar("HP",s.hp,s.maxhp)+bar("SP",s.sp,s.maxsp,"mana")+bar("Food",s.food,1000,"food");const keys=["str","dex","con","int","pow","wc","ac","dam","armour","speed"];$("#stats").innerHTML=keys.map(k=>`<div class="stat"><b>${esc(s[k]??"—")}</b><small>${k}</small></div>`).join("");$("#skills").innerHTML=(state.skills||[]).map(x=>{const cap=x.next_experience==null,title=cap?`${x.name}: ${xpNumber(x.experience)} XP · maximum tracked level`:`${x.name}: ${xpNumber(x.experience)} / ${xpNumber(x.next_experience)} XP · ${xpNumber(x.remaining_experience)} remaining`;return `<span class="skill" title="${esc(title)}">${esc(x.name)} <b>L${x.level}</b><small>${xpNumber(x.experience)}${cap?" XP":` / ${xpNumber(x.next_experience)} · ${x.progress_percent??0}%`}</small></span>`}).join("")}
function money(value){const v=Math.max(0,+value||0),parts=[];for(const [name,n] of [["gold",10000],["silver",100],["copper",1]]){const q=Math.floor((v%({gold:1000000,silver:10000,copper:100}[name]))/n);if(q)parts.push(`${q} ${name}`)}return parts.join(" ")||"0 copper"}
function renderEconomy(){const e=state.economy||{},c=state.conditions||{};$('#wealth').textContent=`Carried: ${money(e.carried)} · Bank: ${e.bank_known?money(e.banked):'unknown'} · Spendable: ${e.bank_known?money(e.total):`${money(e.carried)} + unknown bank`}`;$('#conditions').textContent=`Depletion: ${c.depletion_points_known?`${c.depletion_points}/${c.depletion_threshold} points before restoration`:'unknown'}`}
function glyph(tile){if(tile.player)return '◆';const named=[...tile.objects].reverse().find(o=>o.name||o.target);if(!named)return tile.objects.length?'·':'';if(named.target)return named.friendly?'F':'!';return (named.name||named.face||'·').charAt(0).toUpperCase()}
function renderMap(){const m=state.map;$('#map-name').textContent=[m.name,m.region].filter(Boolean).join(' · ')||'No map loaded';$('#coords').textContent=`${m.x}, ${m.y}`;const map=$('#map');map.style.gridTemplateColumns=`repeat(${m.width},var(--cell))`;map.style.gridTemplateRows=`repeat(${m.height},var(--cell))`;map.innerHTML=m.tiles.map(t=>{const target=[...t.objects].reverse().find(o=>o.target);const cls=t.player?'player':target?(target.friendly?'friend':'enemy'):(t.objects.length?'feature':'');const title=[`world ${t.world_x},${t.world_y}`,...t.objects.map(o=>o.name||o.face).filter(Boolean)].join('\n');return `<button class="tile ${cls}" data-x="${t.x}" data-y="${t.y}" title="${esc(title)}">${esc(glyph(t))}</button>`}).join('');$$('.tile').forEach(b=>b.onclick=()=>post('/api/action',{type:'move',x:+b.dataset.x,y:+b.dataset.y}).catch(e=>toast(e.message,true)))}
function renderTask(){const t=state.task;$('#task').innerHTML=t?`<strong>${esc(t.name)}</strong><br><span>${esc(t.status)}</span>${t.error?` · ${esc(t.error)}`:''}${(t.trace||[]).slice(1).map(s=>`<div class="task-step" style="margin-left:${Math.max(0,s.depth-1)*10}px">↳ ${esc(s.name)} · ${esc(s.status)}${s.detail?`<br><small>${esc(s.detail)}</small>`:''}${s.destination?`<br><code>${esc(s.destination)}${s.coordinates?` @ ${s.coordinates.join(',')}`:''}</code>`:''}</div>`).join('')}`:`<strong>Idle</strong>${state.last_task?`<br><span>Last: ${esc(state.last_task.name)} — ${esc(state.last_task.status)}</span>`:''}`}
function flags(i){return [i.equipped&&'<span class="badge good">equipped</span>',i.applied&&'<span class="badge good">applied</span>',i.locked&&'<span class="badge warn">locked</span>',i.magical&&'<span class="badge">magic</span>'].filter(Boolean).join('')}
function itemAction(type,tag){post('/api/action',{type,tag}).catch(e=>toast(e.message,true))}
function renderInventory(){for(const tag of [...selected])if(!state.inventory.some(i=>i.tag===tag))selected.delete(tag);$('#inventory-summary').textContent=`${state.inventory.length} stacks · ${selected.size} selected`;$('#inventory').innerHTML=state.inventory.map(i=>`<tr><td><input class="pick" type="checkbox" data-tag="${i.tag}" ${selected.has(i.tag)?'checked':''}></td><td><strong>${esc(i.name)}</strong>${i.required_level?`<br><small>Requires level ${i.required_level}</small>`:''}</td><td>${i.quantity}</td><td>${(+i.weight*i.quantity).toFixed(2)}</td><td>${i.condition===255?'—':`${i.condition}%`}</td><td><div class="flags">${flags(i)}</div></td><td><div class="item-actions"><button data-act="apply" data-tag="${i.tag}">Apply</button><button class="secondary" data-act="examine" data-tag="${i.tag}">Look</button><button class="secondary" data-act="lock" data-tag="${i.tag}">${i.locked?'Unlock':'Lock'}</button><button class="danger" data-act="drop" data-tag="${i.tag}">Drop</button></div></td></tr>`).join('');$$('.pick').forEach(x=>x.onchange=()=>{const tag=+x.dataset.tag;x.checked?selected.add(tag):selected.delete(tag);renderInventory()});$$('[data-act]').forEach(x=>x.onclick=()=>itemAction(x.dataset.act,+x.dataset.tag))}
function renderGround(){const items=state.ground||[];$("#ground-summary").textContent=`${items.length} stack${items.length===1?"":"s"}`;$("#ground-items").innerHTML=items.map(i=>`<article class="activity-row"><strong>${esc(i.name)}</strong><span>${i.quantity} available ${i.unpaid?'<span class="badge warn">unpaid</span>':''} ${!i.identified?'<span class="badge warn">unknown</span>':''} ${i.cursed?'<span class="badge warn">cursed</span>':''}</span><small>${esc(i.face||"unknown face")} · type ${i.type||"pending inference"}${i.quality===255?"":` · Q${i.quality}/C${i.condition}`}${i.required_level?` · level ${i.required_level}`:""}${i.inferred_skill_name?` · ${esc(i.inferred_skill_name)}`:""}</small><button class="pickup-item" data-tag="${i.tag}">Pick up</button></article>`).join("")||'<p class="muted">Nothing underfoot.</p>';$$('.pickup-item').forEach(b=>b.onclick=()=>post("/api/action",{type:"pickup",tag:+b.dataset.tag}).catch(e=>toast(e.message,true)))}
function objective(o,p){const progress=p.current!==null?` (${p.current}/${p.required})`:'';return `<div class="objective">${esc(o.quantity)} × ${esc(o.name)}${progress}</div>`}
function monsterBand(s){return s.monster_level_min===null?'monsters unknown':`monsters L${s.monster_level_min}${s.monster_level_max!==s.monster_level_min?`–${s.monster_level_max}`:''}`}
function roamingBand(s){return s.roaming_monster_level_min===null?'':` · neighbor roamers L${s.roaming_monster_level_min}${s.roaming_monster_level_max!==s.roaming_monster_level_min?`–${s.roaming_monster_level_max}`:''}`}
function useFarmSpot(id){const spot=(state.farm_spots||[]).find(x=>x.id===id);if(!spot)return;$("#farm-spot").value=id;$("#farm-zone").value=spot.zone;$("#farm-target").value=spot.target;$("#farm-item").value="";$("#farm-spot-hint").textContent=`Combat ${spot.min_level}–${spot.max_level} · ${monsterBand(spot)}${roamingBand(spot)} · treasure D${spot.treasure_difficulty} · ${spot.circuit&&spot.circuit.length?`${spot.circuit.length}-map circuit · `:""}${spot.notes||spot.map_name}`;toast(`Loaded farm spot: ${spot.name}`)}
function renderFarmCards(){const level=+$('#spot-level').value||0, category=$('#spot-category').value;const spots=(state.farm_spots||[]).filter(s=>(!level||(s.min_level<=level&&level<=s.max_level))&&(!category||s.category===category));$('#farm-spots').innerHTML=spots.map(s=>`<article class="farm-card ${level&&s.min_level<=level&&level<=s.max_level?'recommended':''}"><div class="farm-head"><div><small>Combat ${s.min_level}–${s.max_level} · ${monsterBand(s)}${roamingBand(s)} · treasure D${s.treasure_difficulty} · ${esc(s.category)}</small><h3>${esc(s.name)}</h3></div><button class="small use-spot" data-id="${s.id}">Use</button></div><code title="${esc(s.zone)}">${esc(s.zone)}</code>${s.target?`<span class="badge warn">Target: ${esc(s.target)}</span>`:'<span class="badge">All hostiles</span>'}${s.notable_drops.map(d=>`<div class="drops">◆ ${esc(d)}</div>`).join('')}<p class="muted">${esc(s.notes)}</p></article>`).join('')||'<p class="muted">No curated spots overlap that level and type.</p>';$$('.use-spot').forEach(b=>b.onclick=()=>useFarmSpot(b.dataset.id))}
function renderFarmSpots(){const sig=JSON.stringify(state.farm_spots||[]);if(sig!==lastFarmSig){lastFarmSig=sig;const old=$('#farm-spot').value;$('#farm-spot').innerHTML='<option value="">Choose a known farm spot…</option>'+(state.farm_spots||[]).map(s=>`<option value="${s.id}">Combat ${s.min_level}–${s.max_level} · ${monsterBand(s)} · ${esc(s.name)}</option>`).join('');if([...$('#farm-spot').options].some(o=>o.value===old))$('#farm-spot').value=old}if(!spotLevelInitialized&&state.stats.level){$('#spot-level').value=state.stats.level;spotLevelInitialized=true}renderFarmCards()}
function useNavigationSpot(id){const spot=(state.navigation_spots||[]).find(x=>x.id===id);if(!spot)return;$('#nav-spot').value=id;$('#nav-map').value=spot.destination;$('#nav-x').value=spot.x??'';$('#nav-y').value=spot.y??'';const req=spot.requirements.length?` Requires: ${spot.requirements.join('; ')}.`:'';$('#nav-spot-hint').textContent=`${spot.category} · difficulty ${spot.difficulty} · ${spot.notes||spot.map_name}.${req}`;toast(`Loaded destination: ${spot.name}`)}
function goNavigationSpot(id){const spot=(state.navigation_spots||[]).find(x=>x.id===id);if(!spot)return;post('/api/task',{type:'navigate',destination:spot.destination,x:spot.x,y:spot.y}).catch(e=>toast(e.message,true))}
function renderNavigationCards(){const query=$('#nav-search').value.trim().toLowerCase(),category=$('#nav-category').value;const spots=(state.navigation_spots||[]).filter(s=>(!category||s.category===category)&&(!query||`${s.name} ${s.destination} ${s.notes} ${s.region}`.toLowerCase().includes(query)));$('#navigation-spots').innerHTML=spots.map(s=>`<article class="farm-card"><div class="farm-head"><div><small>${esc(s.category)} · treasure difficulty ${s.difficulty}</small><h3>${esc(s.name)}</h3></div><button class="small go-nav-spot" data-id="${s.id}">Go</button></div><code title="${esc(s.destination)}">${esc(s.destination)}${s.x!==null?` @ ${s.x},${s.y}`:''}</code><span class="badge">${esc(s.map_name||s.region||s.category)}</span>${s.requirements.map(r=>`<div class="drops">Requires: ${esc(r)}</div>`).join('')}<p class="muted">${esc(s.notes)}</p></article>`).join('')||'<p class="muted">No known destinations match these filters.</p>';$$('.go-nav-spot').forEach(b=>b.onclick=()=>goNavigationSpot(b.dataset.id))}
function renderNavigationSpots(){const sig=JSON.stringify(state.navigation_spots||[]);if(sig!==lastNavSig){lastNavSig=sig;const old=$('#nav-spot').value;$('#nav-spot').innerHTML='<option value="">Choose a known destination…</option>'+(state.navigation_spots||[]).map(s=>`<option value="${s.id}">${esc(s.name)} · ${esc(s.category)}</option>`).join('');if([...$('#nav-spot').options].some(o=>o.value===old))$('#nav-spot').value=old}renderNavigationCards()}
function renderQuests(){const sig=JSON.stringify(state.quests);if(sig===lastQuestSig)return;lastQuestSig=sig;const select=$('#quest-select'), old=select.value;select.innerHTML=state.quests.map(q=>`<option value="${esc(q.name)}">${q.order}. ${esc(q.name)} [${q.availability}]</option>`).join('');if([...select.options].some(o=>o.value===old))select.value=old;$('#quests').innerHTML=state.quests.map(q=>`<article class="quest ${q.availability}"><div class="quest-head"><div><small>#${q.order} · ${esc(q.giver)}</small><h3>${esc(q.name)}</h3></div><button class="small run-q" data-name="${esc(q.name)}">${q.availability==='active'?'Resume':q.availability==='completed'?'Review':'Start'}</button></div><div class="quest-meta"><span class="badge ${q.availability==='active'?'warn':q.availability==='completed'?'good':''}">${q.availability}</span><span class="badge">Level ${esc(q.suggested_level)}</span></div><p class="muted">${esc(q.start_location)}</p>${q.requirements.map(r=>`<p class="objective">Requires: ${esc(r)}</p>`).join('')}<details ${q.availability==='active'?'open':''}><summary>${q.parts.length} objective stages</summary>${q.parts.map(p=>`<div class="part"><strong>${esc(p.name)} <span class="badge ${p.ready_to_turn_in?'good':''}">${esc(p.status)}${p.ready_to_turn_in?' · ready':''}</span></strong><p>${esc(p.info)}</p>${p.objectives.map(o=>objective(o,p)).join('')}</div>`).join('')}</details></article>`).join('');$$('.run-q').forEach(b=>b.onclick=()=>post('/api/task',{type:'quest',name:b.dataset.name}).catch(e=>toast(e.message,true)))}
function renderQuestJournal(){const journal=state.quest_journal||[];$('#quest-journal').innerHTML=journal.map(q=>`<article class="quest ${q.status}"><div class="quest-head"><h3>${esc(q.name)}</h3><span class="badge ${q.status==='completed'?'good':'warn'}">${esc(q.status)}</span></div>${q.parts.length?`<details ${q.status!=='completed'?'open':''}><summary>${q.parts.length} reported stage${q.parts.length===1?'':'s'}</summary>${q.parts.map(p=>`<div class="part"><strong>${esc(p.name)} <span class="badge">${esc(p.status)}</span></strong>${p.description?`<p>${esc(p.description)}</p>`:''}${p.current!==null?`<div class="objective">Progress: ${p.current}/${p.required}</div>`:''}</div>`).join('')}</details>`:'<p class="muted">Completed quest</p>'}</article>`).join('')||'<p class="muted">No quests reported. Press “Refresh journal (Q)” to request the current list.</p>'}
function renderMessages(){const box=$('#messages');const atBottom=box.scrollHeight-box.scrollTop-box.clientHeight<35;box.innerHTML=state.messages.map(m=>`<div class="message"><time>${new Date(m.time*1000).toLocaleTimeString()}</time>${esc(m.text)}</div>`).join('');if(atBottom||state.messages.length!==lastMessageCount)box.scrollTop=box.scrollHeight;lastMessageCount=state.messages.length;const d=state.interface;$('#dialogue').innerHTML=d?`<h3>${esc(d.title)}</h3><p>${esc(d.text)}</p>${d.links.map((l,i)=>`<button class="dialog-link" data-index="${i}">${esc(l)}</button>`).join('')}`:'No dialogue open.';$$('.dialog-link').forEach(b=>b.onclick=()=>post('/api/action',{type:'dialog',index:+b.dataset.index}).catch(e=>toast(e.message,true)))}
function renderActivity(){const decisions=$("#activity-mode").value!=="orders",actions=[...(decisions?(state.decisions||[]):(state.actions||[]))].reverse();$("#activity-summary").textContent=`${actions.length} ${decisions?"saved decisions":"recent orders"}`;$("#activity").innerHTML=actions.map(a=>`<article class="activity-row"><time>${new Date(a.time*1000).toLocaleString()}</time><strong>${esc(a.action)}${a.count>1?` ×${a.count}`:""}</strong><span>${esc(a.detail)}</span><small>${esc(a.task||"operator")} · ${esc(a.map||"unknown map")} @ ${a.x},${a.y}</small></article>`).join("")||`<p class="muted">No ${decisions?"decisions":"bot orders"} recorded.</p>`}
function render(){renderHeader();renderStats();renderEconomy();renderMap();renderTask();renderActivity();renderInventory();renderGround();renderFarmSpots();renderNavigationSpots();renderQuests();renderQuestJournal();renderMessages()}
async function poll(){if(busy)return;busy=true;try{const r=await fetch('/api/state',{cache:'no-store'});if(!r.ok)throw Error(r.statusText);state=await r.json();render()}catch(e){$('#connection').textContent=`Dashboard unavailable: ${e.message||e}`;$('#connection-dot').classList.remove('on')}finally{busy=false}}
$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.toggle('active',x===b));$$('.tab-page').forEach(x=>x.classList.toggle('active',x.id===`${b.dataset.tab}-tab`))});
$('#stop-task').onclick=()=>post('/api/task',{type:'stop'}).catch(e=>toast(e.message,true));
$('#activity-mode').onchange=renderActivity;
$('#run-quest').onclick=()=>post('/api/task',{type:'quest',name:$('#quest-select').value}).catch(e=>toast(e.message,true));
$('#run-all').onclick=()=>post('/api/task',{type:'quest',name:'all'}).catch(e=>toast(e.message,true));
$('#farm-spot').onchange=e=>{if(e.target.value)useFarmSpot(e.target.value)};
$('#spot-level').oninput=renderFarmCards;$('#spot-category').onchange=renderFarmCards;
$('#nav-spot').onchange=e=>{if(e.target.value)useNavigationSpot(e.target.value)};
$('#nav-search').oninput=renderNavigationCards;$('#nav-category').onchange=renderNavigationCards;
$("#run-farm").onclick=()=>{const spot=(state.farm_spots||[]).find(x=>x.id===$("#farm-spot").value);const common={until_level:+$("#farm-level").value,combat_skill:$("#farm-skill").value,combat_spell:$("#farm-spell").value};const usesCircuit=spot&&spot.circuit&&spot.circuit.length&&$("#farm-zone").value===spot.zone&&$("#farm-target").value===spot.target;if(usesCircuit)post("/api/task",{type:"farm_circuit",legs:spot.circuit,...common}).catch(e=>toast(e.message,true));else post("/api/task",{type:"farm",zone:$("#farm-zone").value,target:$("#farm-target").value,item:$("#farm-item").value,quantity:+$("#farm-quantity").value,...common}).catch(e=>toast(e.message,true))};
$('#run-nav').onclick=()=>post('/api/task',{type:'navigate',destination:$('#nav-map').value,x:$('#nav-x').value,y:$('#nav-y').value}).catch(e=>toast(e.message,true));
$('#sell-selected').onclick=()=>post('/api/task',{type:'sell_items',merchant:'shop-floor',tags:[...selected]}).catch(e=>toast(e.message,true));
$('#sell-junk').onclick=()=>post('/api/task',{type:'sell_junk',merchant:'shop-floor',patterns:lines('#junk-patterns')}).catch(e=>toast(e.message,true));
$('#bank').onclick=()=>post('/api/task',{type:'bank',banker:$('#banker').value,amount:$('#bank-amount').value}).catch(e=>toast(e.message,true));
$('#deposit').onclick=()=>post('/api/task',{type:'deposit',container:$('#container').value,patterns:lines('#deposit-patterns')}).catch(e=>toast(e.message,true));
$('#refresh-quests').onclick=()=>post('/api/action',{type:'refresh_quests'}).catch(e=>toast(e.message,true));
$('#chat-form').onsubmit=e=>{e.preventDefault();post('/api/action',{type:'chat',text:$('#chat-input').value}).then(()=>$('#chat-input').value='').catch(e=>toast(e.message,true))};
$('#command-form').onsubmit=e=>{e.preventDefault();post('/api/action',{type:'command',command:$('#command-input').value}).then(()=>$('#command-input').value='').catch(e=>toast(e.message,true))};
poll();setInterval(poll,750);
